In [4]:
import numpy as np

np.__version__

'2.2.3'

In [5]:
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\leona\\miniforge3\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\leona\miniforge3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >

In [6]:
result = 0
for i in range(100):
    result += i
print(result)

4950


### A Python integer is a pointer to a position in memory containing all the Python object informaiton, 
### including the bytes that contain the integer value.

# A Python List Is More Than Just a List

In [7]:
lst = list(range(10))
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
type(lst[0])

int

In [9]:
lst_str = [str(c) for c in lst]
print(lst_str)
type(lst_str[0])

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


str

### Each item is a complete Python object, so it is much less efficient

In [10]:
lst_str_het = [True, "2", 3.0, 4]
[type(item) for item in lst_str_het]

[bool, str, float, int]

### Fixed-type NumPy-style arrays lack this flexibility, but are much more efficient for storing and manipulating data

# Fixed-Type Arrays in Python

In [11]:
import array

lst = list(range(10))
arr = array.array('i', lst) # 'i' is a type code indicating the contents are integers
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Creating Arrays from Python Lists

In [12]:
np.array([1, 4, 2, 5, 3]) # can only contain data of the same type

array([1, 4, 2, 5, 3])

### NumPy will upcast arrays according to its type promotion rules; here, integers are upcast to floating point

In [13]:
np.array([3.14, 5, 10, 3, 2])

array([ 3.14,  5.  , 10.  ,  3.  ,  2.  ])

### If we want to explicitly set the data type of the resulting array, we can use the dtype keyword

In [14]:
np.array([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

### Initializing a multidimensional array using a list of lists:

In [15]:
np.array([range(i, i + 3) for i in [2, 4, 6]]) # The inner lists are treated as rows of the resulting two_dimensional array.

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# Creating Arrays from Scratch

In [16]:
# Create a length-10 integer array filled with 0s
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.ones?

Signature: np.ones(shape, dtype=None, order='C', *, device=None, like=None)
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensur

In [19]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [20]:
# this is similar to the built-in range fuction
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
# Create an array of five values evenly spaced betweem 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
np.random.random((3, 3)) # create a 3x3 array of uniformly distributed between 0 and 1

array([[0.38833015, 0.13050605, 0.35263872],
       [0.8915201 , 0.61103235, 0.5729303 ],
       [0.4601755 , 0.75212958, 0.93646717]])

In [23]:
# Create a 3x3 array of normally distributed pseudorandom
# values with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.4188323 ,  0.67794863, -0.46402152],
       [ 0.81963893, -0.1267382 , -0.77289563],
       [ 1.03664777,  0.45784597,  0.21704537]])

In [24]:
# Create a 3x3 array of pseudorandom integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[0, 1, 9],
       [3, 7, 1],
       [1, 1, 2]], dtype=int32)

In [25]:
# Createa a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.empty(3)

array([1., 1., 1.])