In [1]:
import numpy as np

# NumPy Array Attributes

In [2]:
rng = np.random.default_rng(seed = 1701)

In [3]:
arr_rand = rng.integers(10, size=6)
matrix_rand = rng.integers(10, size=(3, 4))
three_d_matrix_rand = rng.integers(10, size=(3, 4, 5))

In [4]:
print(f"arr ndim: {arr_rand}")
print(f"matrix ndim: {matrix_rand}")
print(f"matrix ndim:\n {three_d_matrix_rand}")

arr ndim: [9 4 0 3 8 6]
matrix ndim: [[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]
matrix ndim:
 [[[4 3 5 5 0]
  [8 3 5 2 2]
  [1 8 8 5 3]
  [0 0 8 5 8]]

 [[5 1 6 2 3]
  [1 2 5 6 2]
  [5 2 7 9 3]
  [5 6 0 2 0]]

 [[2 9 4 3 9]
  [9 2 2 4 0]
  [0 3 0 0 2]
  [3 2 7 4 7]]]


In [5]:
print("matrix ndim-3: ", three_d_matrix_rand.ndim)
print("matrix ndim-3 shape: ", three_d_matrix_rand.shape)
print("matrix ndim-3 size: ", three_d_matrix_rand.size)
print("matrix ndim-3: ", three_d_matrix_rand.dtype)

matrix ndim-3:  3
matrix ndim-3 shape:  (3, 4, 5)
matrix ndim-3 size:  60
matrix ndim-3:  int64


# Array Indexing: Accessing Single Elements

In [6]:
arr_rand = rng.integers(11, size=5)
print(arr_rand)
print(arr_rand[0], arr_rand[1], arr_rand[-1], arr_rand[-2], arr_rand[4], arr_rand[3])

[10  4  7  7  6]
10 4 6 7 6 7


In [7]:
matrix_rand = rng.integers(11, size=(3,4))
print(matrix_rand)
print(matrix_rand[0,0])
print(matrix_rand[0,1])
print(matrix_rand[0,-1])
print(matrix_rand[-1, 0])

[[1 3 5 6]
 [5 8 2 5]
 [7 2 8 3]]
1
3
6
7


In [8]:
matrix_rand[0, 0] = 12
print(matrix_rand)

[[12  3  5  6]
 [ 5  8  2  5]
 [ 7  2  8  3]]


# Array Slicing: Accessing Subarrays

## x[start:stop:step]

## One-Dimensional Subarrays

In [31]:
arr_rand

array([10,  4,  7,  7,  6])

In [33]:
arr_rand.size

5

In [28]:
arr_rand[:3] # first three elements

array([10,  4,  7])

In [40]:
arr_rand[3:] # elements after index 3

array([7, 6])

In [17]:
arr_rand[1:4] # middle subarray

array([4, 7, 7])

In [18]:
arr_rand[::2] # every second element

array([10,  7,  6])

In [29]:
arr_rand[1::2] # every second element, starting at index 1

array([4, 7])

### A potentially confusing case is when the step value is negative. In this case,
### the defaults for *start* and *stop* are swapped. This becomes a convenient way 
### to reverse an array.

In [34]:
arr_rand

array([10,  4,  7,  7,  6])

In [35]:
arr_rand[::-1]

array([ 6,  7,  7,  4, 10])

In [36]:
arr_rand[4::-2] # every second element from index 4, reversed

array([ 6,  7, 10])

## Multidimensional Subarrays

In [41]:
matrix_rand

array([[12,  3,  5,  6],
       [ 5,  8,  2,  5],
       [ 7,  2,  8,  3]])

In [42]:
matrix_rand[:2, :3] # first two rows & three columns

array([[12,  3,  5],
       [ 5,  8,  2]])

In [43]:
matrix_rand[:3, ::2] # three rows, every second column

array([[12,  5],
       [ 5,  2],
       [ 7,  8]])

In [44]:
matrix_rand[:3, ::3] # all rows at one steep, all columns at 2 steps

array([[12,  6],
       [ 5,  5],
       [ 7,  3]])

In [45]:
matrix_rand[::-1, ::-1] # all rows & columns, reversed

array([[ 3,  8,  2,  7],
       [ 5,  2,  8,  5],
       [ 6,  5,  3, 12]])

In [46]:
matrix_rand[:, 0] # first column of matrix_rand

array([12,  5,  7])

In [47]:
matrix_rand[2, :] # third row of matrix_rand

array([7, 2, 8, 3])

In [48]:
matrix_rand[0] # equivalent to matrix_rand[0, :]

array([12,  3,  5,  6])

## Subarrays as No-Copy Views

### Unlike Python list slices, NumPy array slices are returned as views rather than copies of the array data

In [49]:
matrix_rand = rng.integers(11, size=(3,4))
matrix_rand

array([[ 8, 10,  3,  8],
       [ 3,  6,  4,  7],
       [ 9,  3,  0,  6]])

In [50]:
matrix_rand_sub_arr = matrix_rand[:2, 1:3]
print(matrix_rand_sub_arr)
matrix_rand_sub_arr[1,0] = 0
matrix_rand_sub_arr[0,1] = 0

[[10  3]
 [ 6  4]]


In [51]:
print(matrix_rand_sub_arr)
print(matrix_rand) # alter matrix_rand_sub_arr alter the original array

[[10  0]
 [ 0  4]]
[[ 8 10  0  8]
 [ 3  0  4  7]
 [ 9  3  0  6]]


#### Some users may find this surprising, but it can be advantageous: for example, when
#### working with large datasets, we can access and process pieces of these datasets
#### without the need to copy the underlying data buffer

# Creating Copis of Arrays

In [52]:
matrix_rand_copy = matrix_rand[:2, :2].copy()
matrix_rand_copy

array([[ 8, 10],
       [ 3,  0]])

# Reshaping of Arrays

In [53]:
np.arange(1, 10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### reshape method will return a no-copy view of the initial array

In [55]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [56]:
x1 = x.reshape(1, 3)
print(x)
print(x1)

[1 2 3]
[[1 2 3]]


In [57]:
x1[0,1] = 8
x2 = x.reshape(3, 1)
print(x)
print(x1)
print(x2)

[1 8 3]
[[1 8 3]]
[[1]
 [8]
 [3]]


### A convenient shorthand for this is to use *np.newaxis* in the slicing syntax:

In [58]:
x[np.newaxis, :]

array([[1, 8, 3]])

In [59]:
x[:, np.newaxis]

array([[1],
       [8],
       [3]])

# Array Concatenation and Splitting

## Concatenation of Arrays

In [144]:
x = np.array([1,2,3])
y = np.array([3,2,1])
print(np.concatenate([x,y])) # list
print(np.concatenate((x,y))) # tuple
print(np.concatenate([x,y,[4, 5, 6]])) # concatenating more than two arrays at once

[1 2 3 3 2 1]
[1 2 3 3 2 1]
[1 2 3 3 2 1 4 5 6]


In [60]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
# vertically
np.concatenate([grid, grid]) # concatenate along the first axis

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [152]:
# horizontally
np.concatenate([grid, grid], axis=1) # concatenate along the second axis

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### For working with array of mixed dimesions, it can be clearer to use the
### np.vstack (vertical stack) function
### np.hstack (horizontal stack) function

In [61]:
np.vstack([x, grid])

array([[1, 8, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [62]:
y = np.array([[99], [99]])
print(y)
np.hstack([grid, y])

[[99]
 [99]]


array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

## Splitting of Arrays

### The opposite of concatenatio is splitting, which is implemented by the functions
### np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices
### giving the split points;

In [63]:
a = [1, 2, 3, 99, 99, 3, 2, 1]

In [66]:
a[:]

[1]