In [2]:
import numpy as np

# NumPy Array Attributes

In [4]:
rng = np.random.default_rng(seed = 1701)

In [5]:
arr_rand = rng.integers(10, size=6)
matrix_rand = rng.integers(10, size=(3, 4))
three_d_matrix_rand = rng.integers(10, size=(3, 4, 5))

In [7]:
print(f"arr ndim: {arr_rand}")
print(f"matrix ndim: {matrix_rand}")
print(f"matrix ndim:\n {three_d_matrix_rand}")

arr ndim: [9 4 0 3 8 6]
matrix ndim: [[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]
matrix ndim:
 [[[4 3 5 5 0]
  [8 3 5 2 2]
  [1 8 8 5 3]
  [0 0 8 5 8]]

 [[5 1 6 2 3]
  [1 2 5 6 2]
  [5 2 7 9 3]
  [5 6 0 2 0]]

 [[2 9 4 3 9]
  [9 2 2 4 0]
  [0 3 0 0 2]
  [3 2 7 4 7]]]


In [9]:
print("matrix ndim-3: ", three_d_matrix_rand.ndim)
print("matrix ndim-3 shape: ", three_d_matrix_rand.shape)
print("matrix ndim-3 size: ", three_d_matrix_rand.size)
print("matrix ndim-3: ", three_d_matrix_rand.dtype)

matrix ndim-3:  3
matrix ndim-3 shape:  (3, 4, 5)
matrix ndim-3 size:  60
matrix ndim-3:  int64


# Array Indexing: Accessing Single Elements

In [15]:
arr_rand = rng.integers(11, size=5)
print(arr_rand)
print(arr_rand[0], arr_rand[1], arr_rand[-1], arr_rand[-2], arr_rand[4], arr_rand[3])

[9 3 0 6 5]
9 3 5 6 5 6


In [17]:
matrix_rand = rng.integers(11, size=(3,4))
print(matrix_rand)
print(matrix_rand[0,0])
print(matrix_rand[0,1])
print(matrix_rand[0,-1])
print(matrix_rand[-1, 0])

[[ 0  0  1 10]
 [ 5  4  8  9]
 [ 1  7  3 10]]
0
0
10
1


In [19]:
matrix_rand[0, 0] = 12
print(matrix_rand)

[[12  0  1 10]
 [ 5  4  8  9]
 [ 1  7  3 10]]


# Array Slicing: Accessing Subarrays

## x[start:stop:step]

## One-Dimensional Subarrays

In [45]:
arr_rand

array([9, 3, 0, 6, 5])

In [46]:
arr_rand[:3] # first three elements

array([9, 3, 0])

In [47]:
arr_rand[3:] # elements after index 3

array([6, 5])

In [48]:
arr_rand[1:4] # middle subarray

array([3, 0, 6])

In [49]:
arr_rand[::2] # every second element

array([9, 0, 5])

In [50]:
arr_rand[1::2] # every second element, starting at index 1

array([3, 6])

### A potentially confusing case is when the step value is negative. In this case,
### the defaults for *start* and *stop* are swapped. This becomes a convenient way 
### to reverse an array.

In [52]:
arr_rand

array([9, 3, 0, 6, 5])

In [53]:
arr_rand[::-1]

array([5, 6, 0, 3, 9])

In [54]:
arr_rand[4::-2] # every second element from index 4, reversed

array([5, 0, 9])

## Multidimensional Subarrays

In [55]:
matrix_rand

array([[12,  0,  1, 10],
       [ 5,  4,  8,  9],
       [ 1,  7,  3, 10]])

In [63]:
matrix_rand[:2, :3] # first two rows & thre columns

array([[12,  0,  1],
       [ 5,  4,  8]])

In [64]:
matrix_rand[:3, ::2] # three rows, every second column

array([[12,  1],
       [ 5,  8],
       [ 1,  3]])

In [81]:
matrix_rand[:3, ::3] # all rows at one steep, all columns at 2 steps

array([[12, 10],
       [ 5,  9],
       [ 1, 10]])

In [82]:
matrix_rand[::-1, ::-1] # all rows & columns, reversed

array([[10,  3,  7,  1],
       [ 9,  8,  4,  5],
       [10,  1,  0, 12]])

In [84]:
matrix_rand[:, 0] # first column of matrix_rand

array([12,  5,  1])

In [88]:
matrix_rand[2, :] # third row of matrix_rand

array([ 1,  7,  3, 10])

In [89]:
matrix_rand[0] # equivalent to matrix_rand[0, :]

array([12,  0,  1, 10])

## Subarrays as No-Copy Views

### Unlike Python list slices, NumPy array slices are returned as views rather than copies of the array data

In [104]:
matrix_rand = rng.integers(11, size=(3,4))
matrix_rand

array([[ 0,  8,  9,  4],
       [ 0,  4, 10,  3],
       [ 2,  5,  5,  5]])

In [105]:
matrix_rand_sub_arr = matrix_rand[:2, 1:3]
print(matrix_rand_sub_arr)
matrix_rand_sub_arr[1,0] = 0
matrix_rand_sub_arr[0,1] = 0

[[ 8  9]
 [ 4 10]]


In [107]:
print(matrix_rand_sub_arr)
print(matrix_rand) # alter matrix_rand_sub_arr alter the original array

[[ 8  0]
 [ 0 10]]
[[ 0  8  0  4]
 [ 0  0 10  3]
 [ 2  5  5  5]]


#### Some users may find this surprising, but it can be advantageous: for example, when
#### working with large datasets, we can access and process pieces of these datasets
#### without the need to copy the underlying data buffer

# Creating Copis of Arrays

In [108]:
matrix_rand_copy = matrix_rand[:2, :2].copy()
matrix_rand_copy

array([[0, 8],
       [0, 0]])

# Reshaping of Arrays

In [112]:
np.arange(1, 10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### reshape method will return a no-copy view of the initial array

In [127]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [130]:
x1 = x.reshape(1, 3)
print(x)
print(x1)

[1 8 3]
[[1 8 3]]


In [131]:
x1[0,1] = 8
x2 = x.reshape(3, 1)
print(x)
print(x1)
print(x2)

[1 8 3]
[[1 8 3]]
[[1]
 [8]
 [3]]


### A convenient shorthand for this is to use *np.newaxis* in the slicing syntax:

In [133]:
x[np.newaxis, :]

array([[1, 8, 3]])

In [135]:
x[:, np.newaxis]

array([[1],
       [8],
       [3]])

# Array Concatenation and Splitting

## Concatenation of Arrays

In [144]:
x = np.array([1,2,3])
y = np.array([3,2,1])
print(np.concatenate([x,y])) # list
print(np.concatenate((x,y))) # tuple
print(np.concatenate([x,y,[4, 5, 6]])) # concatenating more than two arrays at once

[1 2 3 3 2 1]
[1 2 3 3 2 1]
[1 2 3 3 2 1 4 5 6]


In [151]:
grid = np.array([[1, 2, 3], [4, 5, 6]])
# vertically
np.concatenate([grid, grid]) # concatenate along the second axis

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [152]:
# horizontally
np.concatenate([grid, grid], axis=1) # concatenate along the second axis

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### For working with array of mixed dimesions, it can be clearer to use the
### np.vstack (vertical stack) function
### np.hstack (horizontal stack) function

In [153]:
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [155]:
y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

## Splitting of Arrays