# The Slowness of Loops

In [27]:
import numpy as np

rng = np.random.default_rng(seed=1701)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1 / values[i]
    return output

values = rng.integers(1, 10, size=5)
compute_reciprocals(values)

array([0.11111111, 0.25      , 1.        , 0.33333333, 0.125     ])

## Measure the execution time of this code for a large input

In [28]:
big_array = rng.integers(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

283 ms ± 23 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# Introducing Ufuncs

In [29]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.11111111 0.25       1.         0.33333333 0.125     ]
[0.11111111 0.25       1.         0.33333333 0.125     ]


In [30]:
%timeit (1.0 / big_array)

3.59 ms ± 167 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [31]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

### ufunc operations are not limited to one-dimensional arrays.

In [32]:
x = np.arange(9).reshape(3, 3)
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

# Exploring NumPy's Ufuncs
## Ufuncs exist in two flavors: unary ufuncs, which operate on a single input, and binary ufuncs, which opperate on two inputs.
## Array Arithmetic

In [33]:
x = np.arange(4)

In [34]:
print("x      =", x)
print("x + 5  =", x + 5)
print("x - 5  =", x - 5)
print("x * 2  =", x * 2)
print("x / 2  =", x / 2)
print("x // 2 =", x // 2)  # floor division

x      = [0 1 2 3]
x + 5  = [5 6 7 8]
x - 5  = [-5 -4 -3 -2]
x * 2  = [0 2 4 6]
x / 2  = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [35]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [36]:
-(0.5 * x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

### ALL OF THESE ARITHMETIC OPERATIONS ARE SIMPLY CONVENIENT WRAPPERS AROUNG SPECIFIC UFUNCS BUILT INTO NUMPY. FOR EXAMPLE, THE +OPERATOR IS A WRAPPER FOR THE ADD UFUNC.
### Additionally, there are Boolean/bitwise operators; we will explore these in Chapter 9

In [37]:
np.add(x, 2)

array([2, 3, 4, 5])

## ABSOLUTE VALUE

In [38]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

### THE CORRESPONDING NUMPY UFUNC IS NP.ABSOLUTE OR NO.ABS

In [39]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [41]:
np.abs(x)

array([2, 1, 0, 1, 2])

## TRIGONOMETRIC FUNCTIONS

In [42]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x00000189C14DC720>
File:            c:\users\leona\miniforge3\lib\site-packages\numpy\_core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False

In [43]:
theta = np.linspace(0, np.pi, 3)

In [44]:
print("theta      = ", theta)
print("sin(theta)      = ", np.sin(theta))
print("cos(theta)      = ", np.cos(theta))
print("tan(theta)      = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta)      =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta)      =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)      =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [46]:
# inverse trigonometric functions
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


## EXPONENTS AND LOGARITHMS